version: '3.9'

services:
  product_service:
    build: 
      context: ./Product
    ports:
      - "8000:8000"
    command: >
      sh -c "python main.py"
    volumes:
      - ./Product/app:/app
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
  
  order_service:
    build: 
      context: ./Order
    ports:
      - "8001:8001"
    command: >
      sh -c "python main.py"
    volumes:
      - ./Order/app:/app
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      
volumes:
  postgres-data: